name: Build, Test and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build Solution (x64)
        run: msbuild WKDD/WKDD.sln /p:Configuration=Release /p:Platform=x64 /p:IncludePath="D:\a\windows-kernel-driver-development\windows-kernel-driver-development\WKDD" /p:DisablePrecompiledHeaders=true

      - name: Run Tests (x64)
        run: |
          nuget install Microsoft.TestPlatform -Version 17.13.0 -OutputDirectory ./tools
          ./tools/Microsoft.TestPlatform.17.13.0/tools/net462/Common7/IDE/Extensions/TestPlatform/vstest.console.exe WKDD/x64/Release/Tests.dll

      - name: Upload x64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: WKDD-x64
          path: WKDD/x64/Release/WKDD.exe

  release:
    needs: build-and-test
    runs-on: windows-latest
    steps:
      - name: Download x64 Artifact
        uses: actions/download-artifact@v4
        with:
          name: WKDD-x64

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.sha::7 }}
          files: WKDD.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          